//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.28 at 12:07:59 PM CEST 
//


package nl.progaia.esbprocessdraw.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for endpointRefTypeEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="endpointRefTypeEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ENDPOINT"/>
 *     &lt;enumeration value="SERVICE"/>
 *     &lt;enumeration value="PROCESS"/>
 *     &lt;enumeration value="REPLY_TO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "endpointRefTypeEnumeration")
@XmlEnum
public enum EndpointRefTypeEnumeration {

    ENDPOINT,
    SERVICE,
    PROCESS,
    REPLY_TO;

    public String value() {
        return name();
    }

    public static EndpointRefTypeEnumeration fromValue(String v) {
        return valueOf(v);
    }

}
