//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.28 at 12:07:59 PM CEST 
//


package nl.progaia.esbprocessdraw.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.progaia.esbprocessdraw.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.progaia.esbprocessdraw.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RuntimeParamsType.XmlParam }
     * 
     */
    public RuntimeParamsType.XmlParam createRuntimeParamsTypeXmlParam() {
        return new RuntimeParamsType.XmlParam();
    }

    /**
     * Create an instance of {@link RuntimeParamsType.StringParam }
     * 
     */
    public RuntimeParamsType.StringParam createRuntimeParamsTypeStringParam() {
        return new RuntimeParamsType.StringParam();
    }

    /**
     * Create an instance of {@link InitParamsType.XmlParam }
     * 
     */
    public InitParamsType.XmlParam createInitParamsTypeXmlParam() {
        return new InitParamsType.XmlParam();
    }

    /**
     * Create an instance of {@link Process.ExitEndpointList }
     * 
     */
    public Process.ExitEndpointList createProcessExitEndpointList() {
        return new Process.ExitEndpointList();
    }

    /**
     * Create an instance of {@link EventLocationType }
     * 
     */
    public EventLocationType createEventLocationType() {
        return new EventLocationType();
    }

    /**
     * Create an instance of {@link ParamsType }
     * 
     */
    public ParamsType createParamsType() {
        return new ParamsType();
    }

    /**
     * Create an instance of {@link FanoutType }
     * 
     */
    public FanoutType createFanoutType() {
        return new FanoutType();
    }

    /**
     * Create an instance of {@link ItineraryType }
     * 
     */
    public ItineraryType createItineraryType() {
        return new ItineraryType();
    }

    /**
     * Create an instance of {@link Process.TrackingDetails }
     * 
     */
    public Process.TrackingDetails createProcessTrackingDetails() {
        return new Process.TrackingDetails();
    }

    /**
     * Create an instance of {@link FanoutType.Path }
     * 
     */
    public FanoutType.Path createFanoutTypePath() {
        return new FanoutType.Path();
    }

    /**
     * Create an instance of {@link InitParamsType.StringParam.Default }
     * 
     */
    public InitParamsType.StringParam.Default createInitParamsTypeStringParamDefault() {
        return new InitParamsType.StringParam.Default();
    }

    /**
     * Create an instance of {@link InitParamsType.XmlParam.Default }
     * 
     */
    public InitParamsType.XmlParam.Default createInitParamsTypeXmlParamDefault() {
        return new InitParamsType.XmlParam.Default();
    }

    /**
     * Create an instance of {@link StepType }
     * 
     */
    public StepType createStepType() {
        return new StepType();
    }

    /**
     * Create an instance of {@link ItineraryType.Decision }
     * 
     */
    public ItineraryType.Decision createItineraryTypeDecision() {
        return new ItineraryType.Decision();
    }

    /**
     * Create an instance of {@link EndpointRefType }
     * 
     */
    public EndpointRefType createEndpointRefType() {
        return new EndpointRefType();
    }

    /**
     * Create an instance of {@link Process }
     * 
     */
    public Process createProcess() {
        return new Process();
    }

    /**
     * Create an instance of {@link InitParamsType.StringParam }
     * 
     */
    public InitParamsType.StringParam createInitParamsTypeStringParam() {
        return new InitParamsType.StringParam();
    }

    /**
     * Create an instance of {@link ParamsType.StringParam }
     * 
     */
    public ParamsType.StringParam createParamsTypeStringParam() {
        return new ParamsType.StringParam();
    }

    /**
     * Create an instance of {@link InitParamsType }
     * 
     */
    public InitParamsType createInitParamsType() {
        return new InitParamsType();
    }

    /**
     * Create an instance of {@link ItineraryType.Decision.Option }
     * 
     */
    public ItineraryType.Decision.Option createItineraryTypeDecisionOption() {
        return new ItineraryType.Decision.Option();
    }

    /**
     * Create an instance of {@link InterceptorRefType }
     * 
     */
    public InterceptorRefType createInterceptorRefType() {
        return new InterceptorRefType();
    }

    /**
     * Create an instance of {@link Process.TrackingDetails.IdGenerator }
     * 
     */
    public Process.TrackingDetails.IdGenerator createProcessTrackingDetailsIdGenerator() {
        return new Process.TrackingDetails.IdGenerator();
    }

    /**
     * Create an instance of {@link ParamsType.XmlParam }
     * 
     */
    public ParamsType.XmlParam createParamsTypeXmlParam() {
        return new ParamsType.XmlParam();
    }

    /**
     * Create an instance of {@link RuntimeParamsType }
     * 
     */
    public RuntimeParamsType createRuntimeParamsType() {
        return new RuntimeParamsType();
    }

}
