//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.28 at 12:07:59 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sonicsw.com/sonicxq", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.progaia.esbprocessdraw.schema;
