//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.28 at 12:07:59 PM CEST 
//


package nl.progaia.esbprocessdraw.schema;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="exitEndpoint_list" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="exitEndpoint" type="{http://www.sonicsw.com/sonicxq}endpointRefType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="faultEndpoint" type="{http://www.sonicsw.com/sonicxq}endpointRefType" minOccurs="0"/>
 *         &lt;element name="rejectEndpoint" type="{http://www.sonicsw.com/sonicxq}endpointRefType" minOccurs="0"/>
 *         &lt;element name="itinerary" type="{http://www.sonicsw.com/sonicxq}itineraryType"/>
 *         &lt;element name="trackingDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="eventEndpoint" type="{http://www.sonicsw.com/sonicxq}endpointRefType"/>
 *                   &lt;element name="idGenerator">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="params" type="{http://www.sonicsw.com/sonicxq}paramsType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" default="com.sonicsw.xqimpl.service.accessor.ScriptEvaluator" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="trackingLevel" use="required" type="{http://www.sonicsw.com/sonicxq}trackingLevelType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="wsdlUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="qualityOfService" type="{http://www.sonicsw.com/sonicxq}qosType" default="BEST_EFFORT" />
 *       &lt;attribute name="timeToLive" type="{http://www.w3.org/2001/XMLSchema}integer" default="0" />
 *       &lt;attribute name="entry_ref" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "exitEndpointList",
    "faultEndpoint",
    "rejectEndpoint",
    "itinerary",
    "trackingDetails",
    "wsdlUrl"
})
@XmlRootElement(name = "process")
public class Process {

    @XmlElement(name = "exitEndpoint_list")
    protected Process.ExitEndpointList exitEndpointList;
    protected EndpointRefType faultEndpoint;
    protected EndpointRefType rejectEndpoint;
    @XmlElement(required = true)
    protected ItineraryType itinerary;
    protected Process.TrackingDetails trackingDetails;
    protected String wsdlUrl;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected String description;
    @XmlAttribute
    protected QosType qualityOfService;
    @XmlAttribute
    protected BigInteger timeToLive;
    @XmlAttribute(name = "entry_ref")
    protected String entryRef;

    /**
     * Gets the value of the exitEndpointList property.
     * 
     * @return
     *     possible object is
     *     {@link Process.ExitEndpointList }
     *     
     */
    public Process.ExitEndpointList getExitEndpointList() {
        return exitEndpointList;
    }

    /**
     * Sets the value of the exitEndpointList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Process.ExitEndpointList }
     *     
     */
    public void setExitEndpointList(Process.ExitEndpointList value) {
        this.exitEndpointList = value;
    }

    /**
     * Gets the value of the faultEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link EndpointRefType }
     *     
     */
    public EndpointRefType getFaultEndpoint() {
        return faultEndpoint;
    }

    /**
     * Sets the value of the faultEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndpointRefType }
     *     
     */
    public void setFaultEndpoint(EndpointRefType value) {
        this.faultEndpoint = value;
    }

    /**
     * Gets the value of the rejectEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link EndpointRefType }
     *     
     */
    public EndpointRefType getRejectEndpoint() {
        return rejectEndpoint;
    }

    /**
     * Sets the value of the rejectEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndpointRefType }
     *     
     */
    public void setRejectEndpoint(EndpointRefType value) {
        this.rejectEndpoint = value;
    }

    /**
     * Gets the value of the itinerary property.
     * 
     * @return
     *     possible object is
     *     {@link ItineraryType }
     *     
     */
    public ItineraryType getItinerary() {
        return itinerary;
    }

    /**
     * Sets the value of the itinerary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItineraryType }
     *     
     */
    public void setItinerary(ItineraryType value) {
        this.itinerary = value;
    }

    /**
     * Gets the value of the trackingDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Process.TrackingDetails }
     *     
     */
    public Process.TrackingDetails getTrackingDetails() {
        return trackingDetails;
    }

    /**
     * Sets the value of the trackingDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Process.TrackingDetails }
     *     
     */
    public void setTrackingDetails(Process.TrackingDetails value) {
        this.trackingDetails = value;
    }

    /**
     * Gets the value of the wsdlUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWsdlUrl() {
        return wsdlUrl;
    }

    /**
     * Sets the value of the wsdlUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsdlUrl(String value) {
        this.wsdlUrl = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the qualityOfService property.
     * 
     * @return
     *     possible object is
     *     {@link QosType }
     *     
     */
    public QosType getQualityOfService() {
        if (qualityOfService == null) {
            return QosType.BEST_EFFORT;
        } else {
            return qualityOfService;
        }
    }

    /**
     * Sets the value of the qualityOfService property.
     * 
     * @param value
     *     allowed object is
     *     {@link QosType }
     *     
     */
    public void setQualityOfService(QosType value) {
        this.qualityOfService = value;
    }

    /**
     * Gets the value of the timeToLive property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTimeToLive() {
        if (timeToLive == null) {
            return new BigInteger("0");
        } else {
            return timeToLive;
        }
    }

    /**
     * Sets the value of the timeToLive property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTimeToLive(BigInteger value) {
        this.timeToLive = value;
    }

    /**
     * Gets the value of the entryRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryRef() {
        return entryRef;
    }

    /**
     * Sets the value of the entryRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryRef(String value) {
        this.entryRef = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="exitEndpoint" type="{http://www.sonicsw.com/sonicxq}endpointRefType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "exitEndpoint"
    })
    public static class ExitEndpointList {

        @XmlElement(required = true)
        protected List<EndpointRefType> exitEndpoint;

        /**
         * Gets the value of the exitEndpoint property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the exitEndpoint property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExitEndpoint().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EndpointRefType }
         * 
         * 
         */
        public List<EndpointRefType> getExitEndpoint() {
            if (exitEndpoint == null) {
                exitEndpoint = new ArrayList<EndpointRefType>();
            }
            return this.exitEndpoint;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="eventEndpoint" type="{http://www.sonicsw.com/sonicxq}endpointRefType"/>
     *         &lt;element name="idGenerator">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="params" type="{http://www.sonicsw.com/sonicxq}paramsType" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" default="com.sonicsw.xqimpl.service.accessor.ScriptEvaluator" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="trackingLevel" use="required" type="{http://www.sonicsw.com/sonicxq}trackingLevelType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eventEndpoint",
        "idGenerator"
    })
    public static class TrackingDetails {

        @XmlElement(required = true)
        protected EndpointRefType eventEndpoint;
        @XmlElement(required = true)
        protected Process.TrackingDetails.IdGenerator idGenerator;
        @XmlAttribute(required = true)
        protected int trackingLevel;

        /**
         * Gets the value of the eventEndpoint property.
         * 
         * @return
         *     possible object is
         *     {@link EndpointRefType }
         *     
         */
        public EndpointRefType getEventEndpoint() {
            return eventEndpoint;
        }

        /**
         * Sets the value of the eventEndpoint property.
         * 
         * @param value
         *     allowed object is
         *     {@link EndpointRefType }
         *     
         */
        public void setEventEndpoint(EndpointRefType value) {
            this.eventEndpoint = value;
        }

        /**
         * Gets the value of the idGenerator property.
         * 
         * @return
         *     possible object is
         *     {@link Process.TrackingDetails.IdGenerator }
         *     
         */
        public Process.TrackingDetails.IdGenerator getIdGenerator() {
            return idGenerator;
        }

        /**
         * Sets the value of the idGenerator property.
         * 
         * @param value
         *     allowed object is
         *     {@link Process.TrackingDetails.IdGenerator }
         *     
         */
        public void setIdGenerator(Process.TrackingDetails.IdGenerator value) {
            this.idGenerator = value;
        }

        /**
         * Gets the value of the trackingLevel property.
         * 
         */
        public int getTrackingLevel() {
            return trackingLevel;
        }

        /**
         * Sets the value of the trackingLevel property.
         * 
         */
        public void setTrackingLevel(int value) {
            this.trackingLevel = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="params" type="{http://www.sonicsw.com/sonicxq}paramsType" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" default="com.sonicsw.xqimpl.service.accessor.ScriptEvaluator" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "params"
        })
        public static class IdGenerator {

            protected ParamsType params;
            @XmlAttribute(name = "class")
            protected String clazz;

            /**
             * Gets the value of the params property.
             * 
             * @return
             *     possible object is
             *     {@link ParamsType }
             *     
             */
            public ParamsType getParams() {
                return params;
            }

            /**
             * Sets the value of the params property.
             * 
             * @param value
             *     allowed object is
             *     {@link ParamsType }
             *     
             */
            public void setParams(ParamsType value) {
                this.params = value;
            }

            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClazz() {
                if (clazz == null) {
                    return "com.sonicsw.xqimpl.service.accessor.ScriptEvaluator";
                } else {
                    return clazz;
                }
            }

            /**
             * Sets the value of the clazz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClazz(String value) {
                this.clazz = value;
            }

        }

    }

}
